### PR TITLE
add capybara back in

### PR DESCRIPTION
**Pull request by jnoconor**
Capybara is required for this lab but commit d215f82 removed it (presumably by accident). This pull request simply puts it back. See #177 of the lab repo: https://github.com/learn-co-students/sinatra-complex-forms-associations-v-000/issues/177

### CODE REVIEW

**Comment by TheLucasMoore** [comment]
@PeterBell @aturkewi Just had a student run into this same error. So ++ on the merge.

**Comment by aturkewi** [comment]
Looks good. Thanks! And @jnoconor if you make any other PRs the best way to get attention on them is to at mention peter and myself.

Thanks again!

**Comment by PeterBell** [comment]
👍 thanks @aturkewi

**Comment by aturkewi** [comment]
@lukeghenco I'm going to pass this issue over to you :)

**Pull request merged**
