### PR TITLE
Update config.ru

### PR DESCRIPTION
**Pull request by telegraham**
Requests to certain controllers weren't working for a student (with the code out of the box), and this change fixed it. There may be a Better Way — please let me know — but this fix will make the code not broken out of the box, which seems like a priority.

### CODE REVIEW

**Comment by telegraham** [comment]
specifically — the patch to OwnersController

**Comment by telegraham** [comment]
@ndalcin it might also be an *old* sinatra thing — @yberdysh found another issue with 2.0.1 where there's an extra "captures" key in params (for no good reason, later versions of Sinatra remove this, related: https://github.com/sinatra/sinatra/issues/1380)

I'm having her PR an update to the sinatra version in another branch — might be worth seeing if that obviates this PR.

**Comment by telegraham** [comment]
https://github.com/learn-co-curriculum/sinatra-complex-forms-associations/pull/51 @yberdysh 🌮 

^^^^ mentioned PR

**Comment by sgharms** [comment]
So is the preference here to merge #51 or #50?

**Pull request closed without merging**
